name: patents
channels:
  - huggingface
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _tflow_select=2.1.0
  - abseil-cpp=20200225.2
  - absl-py=0.10.0
  - aiohttp=3.6.3
  - arrow-cpp=1.0.1
  - astroid=2.5
  - astunparse=1.6.3
  - async-timeout=3.0.1
  - attrs=20.3.0
  - aws-sdk-cpp=1.7.164
  - backcall=0.2.0
  - beautifulsoup4=4.9.3
  - blas=1.0
  - blinker=1.4
  - boto=2.49.0
  - boto3=1.17.41
  - botocore=1.20.41
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bs4=4.9.3
  - bzip2=1.0.8
  - c-ares=1.16.1
  - ca-certificates=2020.12.5
  - cachetools=4.1.1
  - certifi=2020.12.5
  - cffi=1.14.3
  - chardet=3.0.4
  - click=7.1.2
  - cryptography=3.1.1
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - cupti=10.1.168
  - curl=7.71.1
  - cycler=0.10.0
  - dataclasses=0.7
  - datasets=1.2.1
  - dbus=1.13.18
  - decorator=5.0.6
  - dill=0.3.2
  - et_xmlfile=1.0.1
  - expat=2.3.0
  - faiss-gpu=1.7.0
  - filelock=3.0.12
  - flatten-dict=0.3.0
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fsspec=2021.4.0
  - gast=0.3.3
  - gcsfs=0.6.2
  - gensim=3.8.3
  - gflags=2.2.2
  - glib=2.68.0
  - glog=0.4.0
  - google-api-core=1.25.1
  - google-auth=1.27.1
  - google-auth-oauthlib=0.4.1
  - google-cloud-core=1.6.0
  - google-cloud-storage=1.31.0
  - google-crc32c=1.1.2
  - google-pasta=0.2.0
  - google-resumable-media=1.2.0
  - googleapis-common-protos=1.52.0
  - grpc-cpp=1.30.2
  - grpcio=1.31.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=2.10
  - importlib-metadata=2.0.0
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - isort=5.8.0
  - jdcal=1.4.1
  - jedi=0.17.0
  - jmespath=0.10.0
  - joblib=0.17.0
  - jpeg=9b
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - keras-preprocessing=1.1.0
  - kiwisolver=1.3.1
  - krb5=1.18.2
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - ld_impl_linux-64=2.33.1
  - libcrc32c=1.1.1
  - libcurl=7.71.1
  - libedit=3.1.20191231
  - libevent=2.1.8
  - libfaiss=1.7.0
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libprotobuf=3.12.4
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libtiff=4.2.0
  - libutf8proc=2.5.0
  - libuuid=1.0.3
  - libuv=1.40.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.10
  - libxslt=1.1.34
  - lxml=4.6.3
  - lz4-c=1.9.2
  - markdown=3.3.2
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mccabe=0.6.1
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.0.6
  - mkl_random=1.1.1
  - multidict=4.7.6
  - multiprocess=0.70.11.1
  - ncurses=6.2
  - ninja=1.10.1
  - nltk=3.5
  - numpy=1.19.2
  - numpy-base=1.19.2
  - oauthlib=3.1.0
  - olefile=0.46
  - openpyxl=3.0.7
  - openssl=1.1.1h
  - opt_einsum=3.1.0
  - packaging=20.4
  - pandas=1.1.3
  - parquet-cpp=1.5.1
  - parso=0.8.2
  - pathlib2=2.3.5
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=20.2.4
  - prompt-toolkit=3.0.17
  - protobuf=3.12.4
  - ptyprocess=0.7.0
  - pyarrow=1.0.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pygments=2.8.1
  - pyjwt=1.7.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.7.9
  - python-dateutil=2.8.1
  - python-docx=0.8.10
  - python-xxhash=2.0.0
  - python_abi=3.7
  - pytorch=1.8.1
  - pytz=2020.1
  - pyzmq=20.0.0
  - qt=5.9.7
  - re2=2020.08.01
  - readline=8.0
  - regex=2020.10.15
  - requests=2.24.0
  - requests-oauthlib=1.3.0
  - rsa=4.6
  - s3transfer=0.3.6
  - sacremoses=0.0.43
  - scikit-learn=0.24.1
  - scipy=1.6.2
  - setuptools=50.3.0
  - sip=4.19.8
  - six=1.15.0
  - smart_open=4.2.0
  - snappy=1.1.8
  - soupsieve=2.2.1
  - sqlite=3.33.0
  - tensorboard=2.2.1
  - tensorboard-plugin-wit=1.6.0
  - tensorboardx=2.2
  - tensorflow=2.2.0
  - tensorflow-base=2.2.0
  - tensorflow-estimator=2.2.0
  - tensorflow-gpu=2.2.0
  - tensorflow-hub=0.8.0
  - termcolor=1.1.0
  - threadpoolctl=2.1.0
  - thrift-cpp=0.13.0
  - tk=8.6.10
  - tokenizers=0.10.1
  - toml=0.10.2
  - torchvision=0.2.1
  - tornado=6.1
  - tqdm=4.49.0
  - traitlets=5.0.5
  - transformers=4.4.2
  - typed-ast=1.4.2
  - typing_extensions=3.7.4.3
  - urllib3=1.25.11
  - wcwidth=0.2.5
  - werkzeug=1.0.1
  - wheel=0.35.1
  - wrapt=1.12.1
  - xxhash=0.8.0
  - xz=5.2.5
  - yarl=1.6.2
  - zeromq=4.3.4
  - zipp=3.3.1
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - psutil==5.8.0
    - sentence-transformers==1.0.4
    - sentencepiece==0.1.95
prefix: /home/anfri/anaconda3/envs/patents
